// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveTool(arg1, arg2, arg3) {
  return window['go']['app']['App']['ApproveTool'](arg1, arg2, arg3);
}

export function CancelChat(arg1) {
  return window['go']['app']['App']['CancelChat'](arg1);
}

export function Chat(arg1) {
  return window['go']['app']['App']['Chat'](arg1);
}

export function CompressContext(arg1) {
  return window['go']['app']['App']['CompressContext'](arg1);
}

export function CreateChapter(arg1) {
  return window['go']['app']['App']['CreateChapter'](arg1);
}

export function CreateNovel(arg1) {
  return window['go']['app']['App']['CreateNovel'](arg1);
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function GetArcNodes(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetArcNodes'](arg1, arg2, arg3);
}

export function GetChapterPlans(arg1) {
  return window['go']['app']['App']['GetChapterPlans'](arg1);
}

export function GetChapters(arg1) {
  return window['go']['app']['App']['GetChapters'](arg1);
}

export function GetCharacterRelations(arg1) {
  return window['go']['app']['App']['GetCharacterRelations'](arg1);
}

export function GetCharacters(arg1) {
  return window['go']['app']['App']['GetCharacters'](arg1);
}

export function GetContent(arg1, arg2) {
  return window['go']['app']['App']['GetContent'](arg1, arg2);
}

export function GetLLMConfig() {
  return window['go']['app']['App']['GetLLMConfig']();
}

export function GetLocationRelations(arg1) {
  return window['go']['app']['App']['GetLocationRelations'](arg1);
}

export function GetLocations(arg1) {
  return window['go']['app']['App']['GetLocations'](arg1);
}

export function GetMaxChapterNumber(arg1) {
  return window['go']['app']['App']['GetMaxChapterNumber'](arg1);
}

export function GetModels() {
  return window['go']['app']['App']['GetModels']();
}

export function GetNovels() {
  return window['go']['app']['App']['GetNovels']();
}

export function GetPlatform() {
  return window['go']['app']['App']['GetPlatform']();
}

export function GetSession(arg1) {
  return window['go']['app']['App']['GetSession'](arg1);
}

export function GetSessionMessages(arg1) {
  return window['go']['app']['App']['GetSessionMessages'](arg1);
}

export function GetSessions(arg1) {
  return window['go']['app']['App']['GetSessions'](arg1);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetStoryArcs(arg1) {
  return window['go']['app']['App']['GetStoryArcs'](arg1);
}

export function GetTimelineEntries(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetTimelineEntries'](arg1, arg2, arg3);
}

export function Initialize(arg1) {
  return window['go']['app']['App']['Initialize'](arg1);
}

export function IsInitialized() {
  return window['go']['app']['App']['IsInitialized']();
}

export function SaveContent(arg1) {
  return window['go']['app']['App']['SaveContent'](arg1);
}

export function SaveLLMConfig(arg1) {
  return window['go']['app']['App']['SaveLLMConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SetActiveNovel(arg1) {
  return window['go']['app']['App']['SetActiveNovel'](arg1);
}

export function SetApprovalMode(arg1) {
  return window['go']['app']['App']['SetApprovalMode'](arg1);
}

export function UpdateDataDir(arg1) {
  return window['go']['app']['App']['UpdateDataDir'](arg1);
}
