import { useMemo } from 'react'
import {
  ApproveTool,
  CancelChat,
  Chat,
  CompressContext,
  CreateChapter,
  CreateNovel,
  GetContent,
  SaveContent,
  SetActiveNovel,
  SetApprovalMode,
  GetAppConfig,
  GetChapters,
  GetCharacters,
  GetCharacterRelations,
  GetLocations,
  GetLocationRelations,
  GetNovels,
  GetPlatform,
  GetSettings,
  Initialize,
  IsInitialized,
  SaveSettings,
  GetLLMConfig,
  GetModels,
  GetSession,
  GetSessions,
  GetSessionMessages,
  SaveLLMConfig,
  UpdateDataDir,
  GetMaxChapterNumber,
  GetStoryArcs,
  GetArcNodes,
  GetChapterPlans,
  GetTimelineEntries,
  GetReaderPerspectives,
  GetPreferences,
  CreatePreference,
  UpdatePreference,
  DeletePreference,
} from '@/lib/wailsjs/go/app/App'
import type { app, novel, chapter, config, llm, session, character, location, storyarc, timeline, reader } from '@/lib/wailsjs/go/models'

export function useApp() {
  return useMemo(() => ({
    CancelChat,
    Chat,
    CompressContext,
    CreateChapter,
    CreateNovel,
    GetContent,
    SaveContent,
    GetAppConfig,
    GetChapters,
    GetCharacters,
    GetCharacterRelations,
    GetLocations,
    GetLocationRelations,
    GetNovels,
    GetPlatform,
    GetSettings,
    Initialize,
    IsInitialized,
    SaveSettings,
    SetActiveNovel,
    GetModels,
    GetSession,
    GetSessions,
    GetSessionMessages,
    ApproveTool,
    SetApprovalMode,
    GetLLMConfig,
    SaveLLMConfig,
    UpdateDataDir,
    GetMaxChapterNumber,
    GetStoryArcs,
    GetArcNodes,
    GetChapterPlans,
    GetTimelineEntries,
    GetReaderPerspectives,
    GetPreferences,
    CreatePreference,
    UpdatePreference,
    DeletePreference,
  }), [])
}

export type { app, novel, chapter, config, llm, session, character, location, storyarc, timeline, reader }
