import fs from 'node:fs/promises'
import path from 'node:path'

export function usabilityObservation(input) {
  const scores = {
    discoverability: input.scores?.discoverability ?? 0,
    clickCost: input.scores?.clickCost ?? 0,
    feedbackClarity: input.scores?.feedbackClarity ?? 0,
    errorRecovery: input.scores?.errorRecovery ?? 0,
    keyboardErgonomics: input.scores?.keyboardErgonomics ?? 0,
    informationDensity: input.scores?.informationDensity ?? 0,
    visualReadability: input.scores?.visualReadability ?? 0,
  }
  return {
    surface: input.surface,
    severity: input.severity,
    issueType: input.issueType,
    summary: input.summary,
    screenshot: input.screenshot,
    reproduction: input.reproduction ?? [],
    expected: input.expected,
    actual: input.actual,
    impact: input.impact,
    proposedFix: input.proposedFix,
    scores,
  }
}

export async function writeUsabilityReport(observations, paths) {
  const { phaseOutputRoot, outputDir, repoRoot } = paths
  const artifactPath = (fileName) => path.join(path.relative(repoRoot, outputDir), fileName)
  const scoreRows = observations
    .map((item) => [
      item.surface,
      item.scores.discoverability,
      item.scores.clickCost,
      item.scores.feedbackClarity,
      item.scores.errorRecovery,
      item.scores.keyboardErgonomics,
      item.scores.informationDensity,
      item.scores.visualReadability,
    ].map(markdownCell).join(' | '))
    .map((row) => `| ${row} |`)
    .join('\n')

  const issueRows = observations
    .map((item) => `| ${markdownCell(item.surface)} | ${markdownCell(item.severity)} | ${markdownCell(item.issueType)} | ${markdownCell(item.summary)} | ${markdownCell(artifactPath(item.screenshot))} |`)
    .join('\n')

  const details = observations
    .map((item) => `### ${item.surface}

- Severity: ${item.severity}
- Type: ${item.issueType}
- Screenshot: \`${artifactPath(item.screenshot)}\`
- Reproduction:
${numberedList(item.reproduction)}
- Expected behavior: ${item.expected}
- Actual behavior: ${item.actual}
- Likely user impact: ${item.impact}
- Proposed fix or tracking: ${item.proposedFix}`)
    .join('\n\n')

  const report = `# Phase 13 Usability Report

Generated by \`npm --prefix frontend run test:app:usability\`.

## Scope

This report is generated from deterministic mocked bridge fixtures. It records workflow scoring, severity, affected surface, screenshots, reproduction steps, expected behavior, actual behavior, likely user impact, and proposed fixes. Correctness bugs and ergonomic friction are separated by the Type field.

Artifacts: \`${path.relative(repoRoot, outputDir)}\`

Scoring uses 1-5 where 5 is best. Scores are heuristic product-QA ratings from the scripted browser walkthrough, not performance metrics.

## Workflow Scores

| Surface | Discoverability | Click Cost | Feedback Clarity | Error Recovery | Keyboard Ergonomics | Information Density | Visual Readability |
| --- | --- | --- | --- | --- | --- | --- | --- |
${scoreRows}

## Issues And Observations

| Surface | Severity | Type | Summary | Screenshot |
| --- | --- | --- | --- | --- |
${issueRows}

## Details

${details}

## Reference/Corpus Automation Verdict

The current usability pass confirms the reference surface is reachable, but it deliberately keeps a medium ergonomic-friction item open until Phase 13 proves the normal flow can turn supplied source text into segmented source records, extracted materials, blueprint bindings, and audit feedback without manual corpus plumbing.
`

  await fs.mkdir(phaseOutputRoot, { recursive: true })
  await fs.writeFile(path.join(phaseOutputRoot, 'usability-report.md'), report, 'utf8')
  await fs.writeFile(path.join(outputDir, 'usability-report.md'), report, 'utf8')
}

function markdownCell(value) {
  return String(value ?? '').replaceAll('|', '\\|').replace(/\r?\n/g, '<br>')
}

function numberedList(items) {
  if (!items.length) return '1. No reproduction steps recorded.'
  return items.map((item, index) => `${index + 1}. ${item}`).join('\n')
}
