package llm

// Builtin 内置 provider 模板。APIKey 留空，运行时由用户配置注入。
var Builtin = map[string]Provider{
	"deepseek": {
		Name:        "DeepSeek",
		ChatURL:     "https://api.deepseek.com/v1/chat/completions",
		Temperature: floatPtr(0.7),
		Models: []ModelInfo{
			{
				ID:               "deepseek-v4-flash",
				Name:             "DeepSeek V4 Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				ReasoningLevels:  []string{"high", "max"},
				SupportsVision:   false,
			},
			{
				ID:               "deepseek-v4-pro",
				Name:             "DeepSeek V4 Pro",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  384_000,
				SupportsThinking: true,
				ReasoningLevels:  []string{"high", "max"},
				SupportsVision:   false,
			},
		},
		BuildRequest: nil,
	},
	"doubao": {
			Name:        "Doubao",
			ChatURL:     "https://ark.cn-beijing.volces.com/api/v3/chat/completions",
			Temperature: floatPtr(0.1),
			Models: []ModelInfo{
				{
					ID:               "doubao-seed-2-1-pro-260628",
					Name:             "Seed 2.1 Pro",
					ContextWindow:    256_000,
					MaxOutputTokens:  256_000,
					SupportsThinking: true,
					SupportsVision:   true,
				},
				{
					ID:               "doubao-seed-2-1-turbo-260628",
					Name:             "Seed 2.1 Turbo",
					ContextWindow:    256_000,
					MaxOutputTokens:  256_000,
					SupportsThinking: true,
					SupportsVision:   true,
				},
				{
					ID:               "doubao-seed-2-0-lite-260428",
					Name:             "Seed 2.0 Lite",
					ContextWindow:    256_000,
					MaxOutputTokens:  128_000,
					SupportsThinking: true,
					SupportsVision:   true,
				},
				{
					ID:               "doubao-seed-2-0-code-preview-260215",
					Name:             "Seed 2.0 Code Preview",
					ContextWindow:    256_000,
					MaxOutputTokens:  128_000,
					SupportsThinking: true,
					SupportsVision:   true,
				},
				{
					ID:               "doubao-seed-character-260628",
					Name:             "Seed Character",
					ContextWindow:    128_000,
					MaxOutputTokens:  32_000,
					SupportsThinking: true,
					SupportsVision:   true,
				},
			},
		},
		"qwen": {
		Name:         "Qwen",
		ChatURL:      "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions",
		Temperature:  floatPtr(0.7),
		BuildRequest: qwenBuildRequest,
		Models: []ModelInfo{
			{
				ID:               "qwen3.7-max",
				Name:             "Qwen3.7 Max",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  64_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "qwen3.7-plus",
				Name:             "Qwen3.7 Plus",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  64_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "qwen3.6-plus",
				Name:             "Qwen3.6 Plus",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  64_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "qwen3.6-flash",
				Name:             "Qwen3.6 Flash",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  64_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
		},
	},
	"zhipu": {
		Name:        "GLM",
		ChatURL:     "https://open.bigmodel.cn/api/paas/v4/chat/completions",
		Temperature: floatPtr(1.0),
		Models: []ModelInfo{
			{
				ID:               "glm-5.1",
				Name:             "GLM-5.1",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-5",
				Name:             "GLM-5",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-5-turbo",
				Name:             "GLM-5-Turbo",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-4.7",
				Name:             "GLM-4.7",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-4.7-flashx",
				Name:             "GLM-4.7-FlashX",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "glm-4.7-flash",
				Name:             "GLM-4.7 Flash",
				ContextWindow:    200_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
		},
		BuildRequest: nil,
	},
	"minimax": {
		Name:         "MiniMax",
		ChatURL:      "https://api.minimaxi.com/v1/chat/completions",
		Temperature:  floatPtr(1.0),
		BuildRequest: minimaxBuildRequest,
		Models: []ModelInfo{
			{
				ID:               "MiniMax-M3",
				Name:             "MiniMax M3",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "MiniMax-M2.7",
				Name:             "MiniMax M2.7",
				ContextWindow:    204_800,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "MiniMax-M2.5",
				Name:             "MiniMax M2.5",
				ContextWindow:    204_800,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
		},
	},
	"mimo": {
		Name:         "MiMo",
		ChatURL:      "https://api.xiaomimimo.com/v1/chat/completions",
		Temperature:  floatPtr(1.0),
		BuildHeaders: mimoBuildHeaders,
		Models: []ModelInfo{
			{
				ID:               "mimo-v2.5-pro",
				Name:             "MiMo V2.5 Pro",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
			{
				ID:               "mimo-v2.5",
				Name:             "MiMo V2.5",
				ContextWindow:    1_000_000,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   false,
			},
		},
		BuildRequest: nil,
	},
	"moonshot": {
		Name:         "Kimi",
		ChatURL:      "https://api.moonshot.cn/v1/chat/completions",
		BuildRequest: moonshotBuildRequest,
		Models: []ModelInfo{
			{
				ID:               "kimi-k2.7-code",
				Name:             "Kimi K2.7 Code",
				ContextWindow:    262_144,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "kimi-k2.6",
				Name:             "Kimi K2.6",
				ContextWindow:    262_144,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
			{
				ID:               "kimi-k2.5",
				Name:             "Kimi K2.5",
				ContextWindow:    262_144,
				MaxOutputTokens:  128_000,
				SupportsThinking: true,
				SupportsVision:   true,
			},
		},
	},
}
